name: Affected Module Tests

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Run SolrJ Tests

    runs-on: ubuntu-latest

    steps:
    # Setup
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
        java-package: jdk
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-solr-tests-affected-${{ hashFiles('versions.lock') }}
        restore-keys: |
          ${{ runner.os }}-gradle-solr-tests-affected--
          ${{ runner.os }}-gradle-
    - name: Initialize gradle settings
      run: ./gradlew localSettings
    - name: Test modules affected by this PR
      run: ./gradlew runAffectedUnitTests -Paffected_module_detector.enable
